---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sql.cnrm.cloud.google.com
  resources:
  - sqlsslcerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sql.cnrm.cloud.google.com
  resources:
  - sqlsslcerts/status
  verbs:
  - get
