apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  name: sqeletor-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sqeletor-leader-election
subjects:
- kind: ServiceAccount
  name: sqeletor
  namespace: nais-system
