---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sqeletor.fullname" . }}
  labels:
    {{- include "sqeletor.labels" . | nindent 4 }}
rules:
- apiGroups:
  - sql.cnrm.cloud.google.com
  resources:
  - sqlsslcerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sql.cnrm.cloud.google.com
  resources:
  - sqlsslcerts/status
  verbs:
  - get
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - list
    - create
    - delete
    - update
    - watch
    - patch