dependencies:
  - allOf:
      - cnrm
environmentKinds:
  - tenant
  - legacy
values:
  image.tag:
    displayName: Image tag
    config:
      type: string
  resources.limits.cpu:
    displayName: Cpu limit
    config:
      type: string
  resources.limits.memory:
    displayName: Memory limit
    config:
      type: string
  resources.requests.cpu:
    displayName: Cpu request
    config:
      type: string
  resources.requests.memory:
    displayName: Memory request
    config:
      type: string
